parameters:
    database_host: localhost
    database_port: 3306
    database_name: erudio
    database_user: root
    database_password: erudio
    unix_socket: /tmp/mysql.sock
    mailer_transport: webmail
    mailer_host: ~
    mailer_user: erudio
    mailer_password: erudio
    locale: pt_BR
    secret: 'secret'
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
