sistemas-avaliacao:
    resource: AvaliacaoBundle\Controller\SistemaAvaliacaoController
    type:     rest
    
regimes:
    resource: AvaliacaoBundle\Controller\RegimeController
    type:     rest    
    
tipos-avaliacao:
    resource: AvaliacaoBundle\Controller\TipoAvaliacaoController
    type:     rest
    
habilidades:
    resource: AvaliacaoBundle\Controller\HabilidadeController
    type:     rest
    
conceitos:
    resource: AvaliacaoBundle\Controller\ConceitoController
    type:     rest    
    
avaliacoes-quantitativas:
    resource: AvaliacaoBundle\Controller\AvaliacaoQuantitativaController
    type:     rest
    
avaliacoes-qualitativas:
    resource: AvaliacaoBundle\Controller\AvaliacaoQualitativaController
    type:     rest