services:
    facade.avaliacao.avaliacoes_quantitativas:
      class: AvaliacaoBundle\Service\AvaliacaoQuantitativaFacade
      arguments: ["@doctrine"]
      
    facade.avaliacao.avaliacoes_qualitativas:
      class: AvaliacaoBundle\Service\AvaliacaoQualitativaFacade
      arguments: ["@doctrine"]
    
    facade.avaliacao.habilidades:
      class: AvaliacaoBundle\Service\HabilidadeFacade
      arguments: ["@doctrine"]
      
    facade.avaliacao.conceitos:
      class: AvaliacaoBundle\Service\ConceitoFacade
      arguments: ["@doctrine"]
      
    facade.avaliacao.regimes:
      class: AvaliacaoBundle\Service\RegimeFacade
      arguments: ["@doctrine"]
      
    facade.avaliacao.sistemas_avaliacao:
      class: AvaliacaoBundle\Service\SistemaAvaliacaoFacade
      arguments: ["@doctrine"]
      
    facade.avaliacao.tipos:
      class: AvaliacaoBundle\Service\TipoAvaliacaoFacade
      arguments: ["@doctrine"]
