matriculas:
    resource: MatriculaBundle\Controller\MatriculaController
    type:     rest

enturmacoes:
    resource: MatriculaBundle\Controller\EnturmacaoController
    type:     rest
    
movimentacoes-turma:
    resource: MatriculaBundle\Controller\MovimentacaoTurmaController
    type: rest
    
transferencias:
    resource: MatriculaBundle\Controller\TransferenciaController
    type:     rest
    
desligamentos:
    resource: MatriculaBundle\Controller\DesligamentoController
    type:     rest
    
disciplinas-cursadas:
    resource: MatriculaBundle\Controller\DisciplinaCursadaController
    type: rest
    
medias:
    resource: MatriculaBundle\Controller\MediaController
    type:     rest

notas-quantitativas:
    resource: MatriculaBundle\Controller\NotaQuantitativaController
    type: rest

notas-qualitativas:
    resource: MatriculaBundle\Controller\NotaQualitativaController
    type: rest
   
frequencias:
    resource: MatriculaBundle\Controller\FrequenciaController
    type:     rest
    
uniformes:
    resource: MatriculaBundle\Controller\UniformeController
    type:     rest