usuarios:
    resource: AuthBundle\Controller\UsuarioController
    type:     rest

atribuicoes:
    resource: AuthBundle\Controller\AtribuicaoController
    type:     rest

permissoes:
    resource: AuthBundle\Controller\PermissaoController
    type:     rest

grupos:
    resource: AuthBundle\Controller\GrupoController
    type:     rest

permissoes-grupo:
    resource: AuthBundle\Controller\PermissaoGrupoController
    type:     rest