calendarios:
    resource: CalendarioBundle\Controller\CalendarioController
    type:     rest
    
periodos:
    resource: CalendarioBundle\Controller\PeriodoController
    type:     rest

dias:
    resource: CalendarioBundle\Controller\DiaController
    type:     rest

eventos:
    resource: CalendarioBundle\Controller\EventoController
    type:     rest
    
dias-evento:
    resource: CalendarioBundle\Controller\DiaEventoController
    type:     rest
    
modelo-quadro-horarios:
    resource: CalendarioBundle\Controller\ModeloQuadroHorarioController
    type:     rest
    
quadro-horarios:
    resource: CalendarioBundle\Controller\QuadroHorarioController
    type:     rest
    
horarios:
    resource: CalendarioBundle\Controller\HorarioController
    type: rest
    
horarios-disciplinas:
    resource: CalendarioBundle\Controller\HorarioDisciplinaController
    type: rest
    
aulas:
    resource: CalendarioBundle\Controller\AulaController
    type: rest
    
aula-observacoes:
    resource: CalendarioBundle\Controller\AulaObservacaoController
    type: rest