services:
    facade.calendario.horarios_disciplinas:
        class: CalendarioBundle\Service\HorarioDisciplinaFacade
        arguments: ["@doctrine"]
        calls:
            - [setAulaFacade, ["@facade.calendario.aulas"]]
      
    facade.calendario.aulas:
      class: CalendarioBundle\Service\AulaFacade
      arguments: ["@doctrine", "@logger"]
      calls:
        - [setHorarioDisciplinaFacade, ["@facade.calendario.horarios_disciplinas"]]
