services:
    facade.vinculo.alocacoes:
      class: VinculoBundle\Service\AlocacaoFacade
      arguments: ["@doctrine"]
      calls:
          - [setAtribuicaoFacade, ["@facade.auth.atribuicoes"]]
      
    facade.vinculo.cargos:
      class: VinculoBundle\Service\CargoFacade
      arguments: ["@doctrine"]
      
    facade.vinculo.vinculos:
      class: VinculoBundle\Service\VinculoFacade
      arguments: ["@doctrine"]
      calls:
          - [setUsuarioFacade, ["@facade.auth.usuarios"]]
